pp_index = {
    "bus" : ['BUS_I','BUS_TYPE','PD','QD','GS','BS','BUS_AREA','VM','VA','BASE_KV','ZONE','VMAX','VMIN','LAM_P','LAM_Q','MU_VMAX','MU_VMIN'],
    "branch": ['F_BUS','T_BUS','BR_R','BR_X','BR_B','RATE_A','RATE_B','RATE_C','TAP','SHIFT','BR_STATUS','ANGMIN','ANGMAX','PF','QF','PT','QT','MU_SF','MU_ST','MU_ANGMIN','MU_ANGMAX'],
    "gen": ['GEN_BUS','PG','QG','QMAX','QMIN','VG','MBASE','GEN_STATUS','PMAX','PMIN','PC1','PC2','QC1MIN','QC1MAX','QC2MIN','QC2MAX','RAMP_AGC','RAMP_10','RAMP_30','RAMP_Q','APF','MU_PMAX','MU_PMIN','MU_QMAX','MU_QMIN'],
    "gencost": ['MODEL','STARTUP','SHUTDOWN','NCOST','COST'],
    "dcline": ['F_BUS','T_BUS','BR_STATUS','PF','PT','QF','QT','VF','VT','PMIN','PMAX','QMINF','QMAXF','QMINT','QMAXT','LOSS0','LOSS1'],
    "dclinecost": ['MODEL','STARTUP','SHUTDOWN','NCOST','COST'],
    }

pp_types = {
    "bus" : {
        'BUS_I': int,
        'BUS_TYPE': int,
        'PD': float,
        'QD': float,
        'GS': float,
        'BS': float,
        'BUS_AREA': int,
        'VM': float,
        'VA': float,
        'BASE_KV': float,
        'ZONE': int,
        'VMAX': float,
        'VMIN': float,
        'LAM_P': float,
        'LAM_Q': float,
        'MU_VMAX': float,
        'MU_VMIN': float,
        },
    "branch": {
        'F_BUS': int,
        'T_BUS': int,
        'BR_R': float,
        'BR_X': float,
        'BR_B': float,
        'RATE_A': float,
        'RATE_B': float,
        'RATE_C': float,
        'TAP': float,
        'SHIFT': float,
        'BR_STATUS': int,
        'ANGMIN': float,
        'ANGMAX': float,
        'PF': float,
        'QF': float,
        'PT': float,
        'QT': float,
        'MU_SF': float,
        'MU_ST': float,
        'MU_ANGMIN': float,
        'MU_ANGMAX': float,
        },
    "gen": {
        'GEN_BUS': int,
        'PG': float,
        'QG': float,
        'QMAX': float,
        'QMIN': float,
        'VG': float,
        'MBASE': float,
        'GEN_STATUS': int,
        'PMAX': float,
        'PMIN': float,
        'PC1': float,
        'PC2': float,
        'QC1MIN': float,
        'QC1MAX': float,
        'QC2MIN': float,
        'QC2MAX': float,
        'RAMP_AGC': float,
        'RAMP_10': float,
        'RAMP_30': float,
        'RAMP_Q': float,
        'APF': float,
        'MU_PMAX': float,
        'MU_PMIN': float,
        'MU_QMAX': float,
        'MU_QMIN': float,
        },
    "gencost": {
        'MODEL': int,
        'STARTUP': float,
        'SHUTDOWN': float,
        'NCOST': int,
        'COST': float,
        },
    "dcline": {
        'F_BUS': int,
        'T_BUS': int,
        'BR_STATUS': int,
        'PF': float,
        'PT': float,
        'QF': float,
        'QT': float,
        'VF': float,
        'VT': float,
        'PMIN': float,
        'PMAX': float,
        'QMINF': float,
        'QMAXF': float,
        'QMINT': float,
        'QMAXT': float,
        'LOSS0': float,
        'LOSS1': float,
        },
    "dclinecost": {
        'MODEL': int,
        'STARTUP': float,
        'SHUTDOWN': float,
        'NCOST': int,
        'COST': float,
        },
    }

pp_units = {
    "bus" : {
        'BUS_I': None,
        'BUS_TYPE': None,
        'PD': 'MW',
        'QD': 'MVAr',
        'GS': 'MW',
        'BS': 'MVAr',
        'BUS_AREA': None,
        'VM': 'pu.V',
        'VA': 'deg',
        'BASE_KV': 'kV',
        'ZONE': None,
        'VMAX': 'pu.V',
        'VMIN': 'pu.V',
        'LAM_P': '/MW',
        'LAM_Q': '/MVAr',
        'MU_VMAX': '/pu.V',
        'MU_VMIN': '/pu.V',
        },
    "branch": {
        'F_BUS': None,
        'T_BUS': None,
        'BR_R': 'pu.Ohm',
        'BR_X': 'pu.Ohm',
        'BR_B': 'pu.S',
        'RATE_A': 'MVA',
        'RATE_B': 'MVA',
        'RATE_C': 'MVA',
        'TAP': 'pu',
        'SHIFT': 'deg',
        'BR_STATUS': None,
        'ANGMIN': 'deg',
        'ANGMAX': 'deg',
        'PF': 'MW',
        'QF': 'MVAr',
        'PT': 'MW',
        'QT': 'MVAr',
        'MU_SF': '/MW',
        'MU_ST': '/MW',
        'MU_ANGMIN': '/deg',
        'MU_ANGMAX': '/deg',
        },
    "gen": {
        'GEN_BUS': None,
        'PG': 'MW',
        'QG': 'MVAr',
        'QMAX': 'MVAr',
        'QMIN': 'MVAr',
        'VG': 'pu.V',
        'MBASE': 'MVA',
        'GEN_STATUS': None,
        'PMAX': 'MW',
        'PMIN': 'MW',
        'PC1': 'MW',
        'PC2': 'MW',
        'QC1MIN': 'MVAr',
        'QC1MAX': 'MVAr',
        'QC2MIN': 'MVAr',
        'QC2MAX': 'MVAr',
        'RAMP_AGC': 'MW/min',
        'RAMP_10': 'MW/10min',
        'RAMP_30': 'MW/30min',
        'RAMP_Q': 'MVAr/min',
        'APF': 'pu',
        'MU_PMAX': '/MW',
        'MU_PMIN': '/MW',
        'MU_QMAX': '/MVAr',
        'MU_QMIN': '/MVAr',
        },
    "gencost": {
        'MODEL': None,
        'STARTUP': '$',
        'SHUTDOWN': '$',
        'NCOST': None,
        'COST': None,
        },
    "dcline": {
        'F_BUS': None,
        'T_BUS': None,
        'BR_STATUS': None,
        'PF': 'MW',
        'PT': 'MW',
        'QF': 'MVAr',
        'QT': 'MVAr',
        'VF': 'pu.V',
        'VT': 'pu.V',
        'PMIN': 'MW',
        'PMAX': 'MW',
        'QMINF': 'MVAr',
        'QMAXF': 'MVAr',
        'QMINT': 'MVAr',
        'QMAXT': 'MVAr',
        'LOSS0': 'MW',
        'LOSS1': 'MW/MW',
        },
    "dclinecost": {
        'MODEL': None,
        'STARTUP': '$',
        'SHUTDOWN': '$',
        'NCOST': None,
        'COST': None,
        },
    }

pp_format = {
    "bus" : {
        'BUS_I': '.0f',
        'BUS_TYPE': '.0f',
        'PD': 'g',
        'QD': 'g',
        'GS': 'g',
        'BS': 'g',
        'BUS_AREA': '.0f',
        'VM': 'g',
        'VA': 'g',
        'BASE_KV': 'g',
        'ZONE': '.0f',
        'VMAX': 'g',
        'VMIN': 'g',
        'LAM_P': 'g',
        'LAM_Q': 'g',
        'MU_VMAX': 'g',
        'MU_VMIN': 'g',
        },
    "branch": {
        'F_BUS': '0f',
        'T_BUS': '.0f',
        'BR_R': 'g',
        'BR_X': 'g',
        'BR_B': 'g',
        'RATE_A': 'g',
        'RATE_B': 'g',
        'RATE_C': 'g',
        'TAP': 'g',
        'SHIFT': 'g',
        'BR_STATUS': '.0f',
        'ANGMIN': 'g',
        'ANGMAX': 'g',
        'PF': 'g',
        'QF': 'g',
        'PT': 'g',
        'QT': 'g',
        'MU_SF': 'g',
        'MU_ST': 'g',
        'MU_ANGMIN': 'g',
        'MU_ANGMAX': 'g',
        },
    "gen": {
        'GEN_BUS': '.0f',
        'PG': 'g',
        'QG': 'g',
        'QMAX': 'g',
        'QMIN': 'g',
        'VG': 'g',
        'MBASE': 'g',
        'GEN_STATUS': '.0f',
        'PMAX': 'g',
        'PMIN': 'g',
        'PC1': 'g',
        'PC2': 'g',
        'QC1MIN': 'g',
        'QC1MAX': 'g',
        'QC2MIN': 'g',
        'QC2MAX': 'g',
        'RAMP_AGC': 'g',
        'RAMP_10': 'g',
        'RAMP_30': 'g',
        'RAMP_Q': 'g',
        'APF': 'g',
        'MU_PMAX': 'g',
        'MU_PMIN': 'g',
        'MU_QMAX': 'g',
        'MU_QMIN': 'g',
        },
    "gencost": {
        'MODEL': '.0f',
        'STARTUP': 'g',
        'SHUTDOWN': 'g',
        'NCOST': '.0f',
        'COST': '.0f',
        },
    "dcline": {
        'F_BUS': '.0f',
        'T_BUS': '.0f',
        'BR_STATUS': '.0f',
        'PF': 'g',
        'PT': 'g',
        'QF': 'g',
        'QT': 'g',
        'VF': 'g',
        'VT': 'g',
        'PMIN': 'g',
        'PMAX': 'g',
        'QMINF': 'g',
        'QMAXF': 'g',
        'QMINT': 'g',
        'QMAXT': 'g',
        'LOSS0': 'g',
        'LOSS1': 'g',
        },
    "dclinecost": {
        'MODEL': '.0f',
        'STARTUP': 'g',
        'SHUTDOWN': 'g',
        'NCOST': '.0f',
        'COST': '.0f',
        },
    }

pp_check = {
    "bus" : {
        'BUS_I': lambda x: x>=0 and x<30000,
        'BUS_TYPE': lambda x: x in [1,2,3,4],
        'PD': lambda x: True,
        'QD': lambda x: True,
        'GS': lambda x: True,
        'BS': lambda x: True,
        'BUS_AREA': lambda x: x>0 and x<=100,
        'VM': lambda x: x>=0,
        'VA': lambda x: x>=-360 and x<=360,
        'BASE_KV': lambda x: x>=0,
        'ZONE': lambda x: x>0 and x<1000,
        'VMAX': lambda x: x>0,
        'VMIN': lambda x: x>0,
        'LAM_P': lambda x: True,
        'LAM_Q': lambda x: True,
        'MU_VMAX': lambda x: True,
        'MU_VMIN': lambda x: True,
        },
    "branch": {
        'F_BUS': lambda x: x>=0 and x<30000,
        'T_BUS': lambda x: x>=0 and x<30000,
        'BR_R': lambda x: True,
        'BR_X': lambda x: True,
        'BR_B': lambda x: True,
        'RATE_A': lambda x: x>0,
        'RATE_B': lambda x: x>=0,
        'RATE_C': lambda x: x>=0,
        'TAP': lambda x: x>=0,
        'SHIFT': lambda x: x>=-360 and x<=360,
        'BR_STATUS': lambda x: x in [0,1],
        'ANGMIN': lambda x: x>=-360 and x<=360,
        'ANGMAX': lambda x: x>=-360 and x<=360,
        'PF': lambda x: True,
        'QF': lambda x: True,
        'PT': lambda x: True,
        'QT': lambda x: True,
        'MU_SF': lambda x: True,
        'MU_ST': lambda x: True,
        'MU_ANGMIN': lambda x: True,
        'MU_ANGMAX': lambda x: True,
        },
    "gen": {
        'GEN_BUS': lambda x: x>=0 and x<30000,
        'PG': lambda x: True,
        'QG': lambda x: True,
        'QMAX': lambda x: True,
        'QMIN': lambda x: True,
        'VG': lambda x: x>0,
        'MBASE': lambda x: x>0,
        'GEN_STATUS': lambda x: x in [0,1],
        'PMAX': lambda x: x>=0,
        'PMIN': lambda x: x>=0,
        'PC1': lambda x: True,
        'PC2': lambda x: True,
        'QC1MIN': lambda x: True,
        'QC1MAX': lambda x: True,
        'QC2MIN': lambda x: True,
        'QC2MAX': lambda x: True,
        'RAMP_AGC': lambda x: x>=0,
        'RAMP_10': lambda x: x>=0,
        'RAMP_30': lambda x: x>=0,
        'RAMP_Q': lambda x: x>=0,
        'APF': lambda x: x>=0,
        'MU_PMAX': lambda x: True,
        'MU_PMIN': lambda x: True,
        'MU_QMAX': lambda x: True,
        'MU_QMIN': lambda x: True,
        },
    "gencost": {
        'MODEL': lambda x: x in [1,2],
        'STARTUP': lambda x: x>=0,
        'SHUTDOWN': lambda x: x>=0,
        'NCOST': lambda x: x>0,
        'COST': lambda x: True,
        },
    "dcline": {
        'F_BUS': lambda x: x>=0 and x<30000,
        'T_BUS': lambda x: x>=0 and x<30000,
        'BR_STATUS': lambda x: x in [0,1],
        'PF': lambda x: True,
        'PT': lambda x: True,
        'QF': lambda x: True,
        'QT': lambda x: True,
        'VF': lambda x: x>0,
        'VT': lambda x: x>0,
        'PMIN': lambda x: True,
        'PMAX': lambda x: True,
        'QMINF': lambda x: True,
        'QMAXF': lambda x: True,
        'QMINT': lambda x: True,
        'QMAXT': lambda x: True,
        'LOSS0': lambda x: x>=0,
        'LOSS1': lambda x: x>=0,
        },
    "dclinecost": {
        'MODEL': lambda x: x in [1,2],
        'STARTUP': lambda x: x>=0,
        'SHUTDOWN': lambda x: x>=0,
        'NCOST': lambda x: x>0,
        'COST': lambda x: True,
        },
    }
