name: validate

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10","3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Test python${{matrix.python-version}} on ${{matrix.os}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
        run: |
          python${{matrix.python-version}} -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip -r requirements.txt
          cd tests
          python3 test.py


